// Wanderlust constants
export const GRADIENT_SEL_STYLE				= 'GRADIENT_SEL_STYLE';
export const GRADIENT_SEL_COLOR				= 'GRADIENT_SEL_COLOR';
export const GRADIENT_SEL_DIRECTION			= 'GRADIENT_SEL_DIRECTION';
